title: Project
pages: false
files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea
icon:  folder-open
fields:
  title:
    label: Title
    type:  text
    width: 3/4
  year:
    label: Year
    type:  text
    width: 1/4
  cover_image:
    label: Cover images
    type: image
  text:
    label: Text
    type:  textarea
  client:
    label: Client
    type: text
  Tools:
    label: Tools
    type: text
